[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
blocktowin = "HgDCYQefJ2eWbi4MKXLhuNTVAYzVyD6pxrWnk79Zqs57"

[programs.devnet]
blocktowin = "HgDCYQefJ2eWbi4MKXLhuNTVAYzVyD6pxrWnk79Zqs57"

[programs.mainnet]
blocktowin = "HgDCYQefJ2eWbi4MKXLhuNTVAYzVyD6pxrWnk79Zqs57"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/createcompetition.ts"
